[package]
name = "hana-host"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace
hana-oracle.workspace = true
hana-client.workspace = true
hana-celestia.workspace = true

# Kona
kona-preimage = { workspace = true, features = ["std"] }
kona-proof = { workspace = true, features = ["std"] }
kona-derive.workspace = true
kona-providers-alloy.workspace = true
kona-std-fpvm.workspace = true

# Alloy
alloy-rlp.workspace = true
alloy-provider = { workspace = true, features = ["reqwest"] }
alloy-rpc-client.workspace = true
alloy-transport-http.workspace = true
alloy-primitives = { workspace = true, features = ["serde"] }
alloy-rpc-types.workspace = true
alloy-transport.workspace = true
alloy-sol-types.workspace = true
alloy-contract.workspace = true
alloy-trie.workspace = true

# Op Alloy
op-alloy-rpc-types-engine = { workspace = true, features = ["serde"] }
op-alloy-network.workspace = true

# Maili
maili-genesis = { workspace = true, features = ["std", "serde"] }

# General
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
reqwest.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive", "env"] }
tracing-subscriber = { workspace = true, features = ["fmt"] }

# Celestia
celestia-types.workspace = true
celestia-rpc.workspace = true

kona-host = { git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.9"}

[dev-dependencies]
proptest.workspace = true

[features]
default = ["celestia"]
celestia = []

[[bin]]
name = "kona-host"
path = "src/bin/host.rs"

