[package]
name = "hana-celestia"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace
kona-derive.workspace = true
kona-protocol.workspace = true

alloy-primitives.workspace = true

# Celestia
celestia-types.workspace = true

tracing.workspace = true

async-trait.workspace = true